Andriy
BogdanKalysh/budget_manager_app pull request #14
Opened 2021-04-25 20:04 UTC by Pasemko

2021-04-25 20:13 UTC, BogdanKalysh approved these changes

2021-04-25 20:14 UTC, VolodymyrVoloshyn02 approved these changes

2021-04-25 20:23 UTC, Nazar-TK approved these changes

2021-04-26 12:51 UTC, AndriyFedorenko requested changes

2021-04-26 12:51 UTC, AndriyFedorenko commented on DAL/headers/constants.h
> +    const QString DBTYPE = "QPSQL";
It is ok as a temporary solution but it should be fixed in the future.

2021-04-26 12:51 UTC, AndriyFedorenko commented on DAL/headers/repositories/userrepository.h
> +
remove empty line

2021-04-26 12:51 UTC, AndriyFedorenko commented on DAL/sources/repositories/categoryrepository.cpp
> +QVector<Category> CategoryRepository::select(QString query)
Parameter query should be passed as const reference

2021-04-26 12:51 UTC, AndriyFedorenko commented on DAL/sources/repositories/categoryrepository.cpp
> +    else
Please add curly braces

2021-04-26 12:51 UTC, AndriyFedorenko commented on DAL/sources/repositories/categoryrepository.cpp
> +    {
You are using different styles. 
You should decide if you are using 
if () { 
or
 if ()
{

2021-04-26 12:51 UTC, AndriyFedorenko commented on DAL/sources/repositories/categoryrepository.cpp
> +            type = "income";
Please move this text to constants.

2021-04-26 12:51 UTC, AndriyFedorenko commented on DAL/sources/repositories/categoryrepository.cpp
> +        if(object.getType() == 0)
better to use operator ? :

2021-04-26 12:51 UTC, AndriyFedorenko commented on DAL/sources/repositories/querybuilders.cpp
> +    if(fields.size() == values.size()) {
The same

2021-04-26 12:51 UTC, AndriyFedorenko commented on DAL/sources/repositories/transactionrepository.cpp
> +bool TransactionRepository::update(Transaction &object)
You are not changing object. Please use const

2021-04-27 12:47 UTC, AndriyFedorenko approved these changes
Generally looks good but please add a reference for all QString parameters (This is the rule for all complicated types)

2021-04-27 12:47 UTC, AndriyFedorenko commented on DAL/headers/models/user.h
> +    QString setName(const QString name);
Please add reference

2021-04-27 12:47 UTC, AndriyFedorenko commented on DAL/sources/models/category.cpp
> +Category::Category(const int id, const QString name, const Type type, const QColor color, const int userId)
Please add reference

2021-04-27 12:47 UTC, AndriyFedorenko commented on DAL/sources/models/category.cpp
> +QString Category::setName(const QString name)
Please add reference

2021-04-27 12:47 UTC, AndriyFedorenko commented on DAL/sources/models/transaction.cpp
>      return "Success";
it is more effective to use an enumeration for a returning value

2021-04-27 12:47 UTC, AndriyFedorenko commented on DAL/sources/models/transaction.cpp
> +QString Transaction::setDescription(const QString description)
Please add a reference for all QString parameters

2021-04-27 12:47 UTC, AndriyFedorenko commented on DAL/sources/repositories/userrepository.cpp
> +
remove empty line

2021-04-27 15:24 UTC, merged