Bohdan
BogdanKalysh/budget_manager_app pull request #15
Opened 2021-04-26 11:19 UTC by BogdanKalysh

2021-04-26 11:56 UTC, Pasemko approved these changes

2021-04-26 12:34 UTC, AndriyFedorenko requested changes
Please read about polymorphism in C++ and how to use Interfaces. 
Pay attention to code formatting and some redundant empty lines and spaces

2021-04-26 12:34 UTC, AndriyFedorenko commented on budget_manager_frontend/headers/loginWindow.h
> +    QNetworkAccessManager* manager = new QNetworkAccessManager;
It is better to use smart pointers

2021-04-26 12:34 UTC, AndriyFedorenko commented on budget_manager_frontend/headers/parsers/transactionparser.h
> +class TransactionParser: IJsonParser<Transaction>
You do not inherit the interface. You inherit implementation only.

2021-04-26 12:34 UTC, AndriyFedorenko commented on budget_manager_frontend/headers/parsers/userparser.h
> +class UserParser: IJsonParser<User>
You do not inherit the interface. You inherit implementation only.

2021-04-26 12:34 UTC, AndriyFedorenko commented on budget_manager_frontend/sources/mainWindow.cpp
> +    if(ui->expenceRadioButton->isChecked()){
Code is duplicating and very weird logic. Please simplify this code.

2021-04-26 12:34 UTC, AndriyFedorenko commented on budget_manager_frontend/sources/mainWindow.cpp
> +        CategoryParser parser;
You are inheriting from IJsonParser. You should use this interface.

2021-04-26 12:34 UTC, AndriyFedorenko commented on budget_manager_frontend/sources/mainWindow.cpp
> +        TransactionParser parser;
You should use polymorphism.

2021-04-26 12:34 UTC, AndriyFedorenko commented on budget_manager_frontend/sources/mainWindow.cpp
> +    int amount;
Please assign a default value.

2021-04-26 12:34 UTC, AndriyFedorenko commented on budget_manager_frontend/sources/mainWindow.cpp
> +        amount = ui->amountInputLine->text().toInt();
I suppose there should be +

2021-04-26 12:34 UTC, AndriyFedorenko commented on budget_manager_frontend/sources/mainWindow.cpp
> +    foreach(Category cat, categories){
Please use https://en.cppreference.com/w/cpp/language/range-for

2021-04-26 12:34 UTC, AndriyFedorenko commented on budget_manager_frontend/sources/mainWindow.cpp
> +    foreach(Category cat, categories){
generally better to use algorithms for instance find_if

2021-04-26 12:34 UTC, AndriyFedorenko commented on budget_manager_frontend/sources/models/transaction.cpp
> +
remove empty line

2021-04-26 12:34 UTC, AndriyFedorenko commented on budget_manager_frontend/sources/parsers/transactionparser.cpp
> +
remove empty line

2021-04-26 12:34 UTC, AndriyFedorenko commented on budget_manager_frontend/sources/parsers/transactionparser.cpp
> +
remove empty lines

2021-04-26 12:34 UTC, AndriyFedorenko commented on budget_manager_frontend/sources/mainWindow.cpp
> +    else{
is this format for curly braces correct?

2021-04-26 12:34 UTC, AndriyFedorenko commented on budget_manager_frontend/sources/mainWindow.cpp
> +    }else{
is this format for curly braces correct?

2021-04-26 12:34 UTC, AndriyFedorenko commented on budget_manager_frontend/headers/mainWindow.h
> +
remove empty line

2021-04-30 00:33 UTC, BogdanKalysh commented on budget_manager_frontend/headers/builders/transactionJsonBuilder.h
> +class TransactionJsonBuilder: IJsonBuilder<Transaction>
Changed inherit mode to public

2021-04-30 00:33 UTC, BogdanKalysh commented on budget_manager_frontend/headers/builders/userJsonBuilder.h
> +class UserJsonBuilder: IJsonBuilder<User>
Changed inherit mode to public

2021-04-30 00:34 UTC, BogdanKalysh commented on budget_manager_frontend/headers/loginWindow.h
> +    QNetworkAccessManager* manager = new QNetworkAccessManager;
Used QSharedPointer for this

2021-04-30 00:34 UTC, BogdanKalysh commented on budget_manager_frontend/headers/mainWindow.h
> +
removed

2021-04-30 00:35 UTC, BogdanKalysh commented on budget_manager_frontend/headers/parsers/transactionparser.h
> +class TransactionParser: IJsonParser<Transaction>
Changed inherit mode to public

2021-04-30 00:36 UTC, BogdanKalysh commented on budget_manager_frontend/headers/parsers/userparser.h
> +class UserParser: IJsonParser<User>
Changed inherit mode to public

2021-04-30 00:37 UTC, BogdanKalysh commented on budget_manager_frontend/sources/mainWindow.cpp
> +        CategoryParser parser;
Used QSharedPointer for parser and made it IJsonParser initialised as CategoryParser

2021-04-30 00:38 UTC, BogdanKalysh commented on budget_manager_frontend/sources/mainWindow.cpp
> +    if(ui->expenceRadioButton->isChecked()){
Removed code duplication and simplified

2021-04-30 00:38 UTC, BogdanKalysh commented on budget_manager_frontend/sources/mainWindow.cpp
> +    }else{
fixed braces format

2021-04-30 00:39 UTC, BogdanKalysh commented on budget_manager_frontend/sources/mainWindow.cpp
> +        TransactionParser parser;
Used IJsonParser

2021-04-30 00:39 UTC, BogdanKalysh commented on budget_manager_frontend/sources/mainWindow.cpp
> +    else{
fixed braces format

2021-04-30 00:39 UTC, BogdanKalysh commented on budget_manager_frontend/sources/mainWindow.cpp
> +    int amount;
fixed

2021-04-30 00:40 UTC, BogdanKalysh commented on budget_manager_frontend/sources/mainWindow.cpp
> +        amount = ui->amountInputLine->text().toInt();
Removed if statement at all, it should be like this

2021-04-30 00:41 UTC, BogdanKalysh commented on budget_manager_frontend/sources/mainWindow.cpp
> +    foreach(Category cat, categories){
used for instead of foreach everywhere

2021-04-30 00:42 UTC, BogdanKalysh commented on budget_manager_frontend/sources/mainWindow.cpp
> +    foreach(Category cat, categories){
Found way to just get id from combobox without searching it in vector

2021-04-30 00:43 UTC, BogdanKalysh commented on budget_manager_frontend/sources/models/transaction.cpp
> +
Removed

2021-04-30 00:43 UTC, BogdanKalysh commented on budget_manager_frontend/sources/parsers/transactionparser.cpp
> +
Removed

2021-04-30 17:03 UTC, Nazar-TK reviewed
Good

2021-04-30 18:20 UTC, merged